name: Github User Watch

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
         
      - id: state
        run: echo ::set-output name=state::$(cat ghuserprojects.state.json)
      - uses: ste-xx/gh-user-projects-rss-action@main
        with:
          state: ${{ steps.state.outputs.state }}
          feedUrl: https://raw.githubusercontent.com/ste-xx/rss-watch/main/ghuserprojects.json
          names: |
            [
              "awslabs",
              "aws",
              "google",
              "GoogleChrome",
              "GoogleChromeLabs",
              "facebook",
              "facebookresearch",
              "microsoft",
              "Netflix",
              "tailwindlabs",
              "github",
              "vercel",
              "actions"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: rss
      - run: | 
          cat <<EOF > ghuserprojects.json
          ${{ steps.rss.outputs.jsonFeed }}
          EOF
      - run: | 
         cat <<EOF > ghuserprojects.state.json
         ${{ steps.rss.outputs.state }}
         EOF
         
      - uses: EndBug/add-and-commit@v9
