name: RSS Watch

on:
  schedule:
    - cron: "40 0 * * *"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ste-xx/hackernews-to-rss-action@main
        with:
          state: | 
            {
            }
        id: hn
      - run: | 
          cat <<EOF > hn.json
          ${{ steps.hn.outputs.jsonFeed }}
          EOF
      - run: | 
         cat <<EOF > hn.state.json
         ${{ steps.hn.outputs.state }}
         EOF
          
      - uses: EndBug/add-and-commit@v9
